itemdict = {
    "ITEM_NONE" : "",
    "ITEM_MASTER_BALL" : "Master Ball",
    "ITEM_ULTRA_BALL" : "Ultra Ball",
    "ITEM_GREAT_BALL" : "Great Ball",
    "ITEM_POKE_BALL" : "Poke Ball",
    "ITEM_SAFARI_BALL" : "Safari Ball",
    "ITEM_NET_BALL" : "Net Ball",
    "ITEM_DIVE_BALL" : "Dive Ball",
    "ITEM_NEST_BALL" : "Nest Ball",
    "ITEM_REPEAT_BALL" : "Repeat Ball",
    "ITEM_TIMER_BALL" : "Timer Ball",
    "ITEM_LUXURY_BALL" : "Luxury Ball",
    "ITEM_PREMIER_BALL" : "Premier Ball",
    "ITEM_POTION" : "",
    "ITEM_ANTIDOTE" : "",
    "ITEM_BURN_HEAL" : "",
    "ITEM_ICE_HEAL" : "",
    "ITEM_AWAKENING" : "",
    "ITEM_PARALYZE_HEAL" : "",
    "ITEM_FULL_RESTORE" : "",
    "ITEM_MAX_POTION" : "",
    "ITEM_HYPER_POTION" : "",
    "ITEM_SUPER_POTION" : "",
    "ITEM_FULL_HEAL" : "",
    "ITEM_REVIVE" : "",
    "ITEM_MAX_REVIVE" : "",
    "ITEM_FRESH_WATER" : "",
    "ITEM_SODA_POP" : "",
    "ITEM_LEMONADE" : "",
    "ITEM_MOOMOO_MILK" : "",
    "ITEM_ENERGY_POWDER" : "",
    "ITEM_ENERGY_ROOT" : "",
    "ITEM_HEAL_POWDER" : "",
    "ITEM_REVIVAL_HERB" : "",
    "ITEM_ETHER" : "",
    "ITEM_MAX_ETHER" : "",
    "ITEM_ELIXIR" : "",
    "ITEM_MAX_ELIXIR" : "",
    "ITEM_LAVA_COOKIE" : "",
    "ITEM_BLUE_FLUTE" : "",
    "ITEM_YELLOW_FLUTE" : "",
    "ITEM_RED_FLUTE" : "",
    "ITEM_BLACK_FLUTE" : "",
    "ITEM_WHITE_FLUTE" : "",
    "ITEM_BERRY_JUICE" : "Berry Juice",
    "ITEM_SACRED_ASH" : "",
    "ITEM_SHOAL_SALT" : "",
    "ITEM_SHOAL_SHELL" : "",
    "ITEM_RED_SHARD" : "",
    "ITEM_BLUE_SHARD" : "",
    "ITEM_YELLOW_SHARD" : "",
    "ITEM_GREEN_SHARD" : "",
    "ITEM_RAGE_CANDY_BAR" : "",
    "ITEM_OLD_GATEAU" : "",
    "ITEM_CASTELIACONE" : "",
    "ITEM_DREAM_MIST" : "",
    "ITEM_SHALOUR_SABLE" : "",
    "ITEM_HEALTH_WING" : "",
    "ITEM_MUSCLE_WING" : "",
    "ITEM_RESIST_WING" : "",
    "ITEM_GENIUS_WING" : "",
    "ITEM_CLEVER_WING" : "",
    "ITEM_SWIFT_WING" : "",
    "ITEM_HP_UP" : "",
    "ITEM_PROTEIN" : "",
    "ITEM_IRON" : "",
    "ITEM_CARBOS" : "",
    "ITEM_CALCIUM" : "",
    "ITEM_RARE_CANDY" : "",
    "ITEM_PP_UP" : "",
    "ITEM_ZINC" : "",
    "ITEM_PP_MAX" : "",
    "ITEM_DYNAMAX_CANDY" : "",
    "ITEM_GUARD_SPEC" : "",
    "ITEM_DIRE_HIT" : "",
    "ITEM_X_ATTACK" : "",
    "ITEM_X_DEFEND" : "",
    "ITEM_X_SPEED" : "",
    "ITEM_X_ACCURACY" : "",
    "ITEM_X_SPECIAL" : "",
    "ITEM_POKE_DOLL" : "",
    "ITEM_FLUFFY_TAIL" : "",
    "ITEM_BIG_MALASADA" : "",
    "ITEM_SUPER_REPEL" : "",
    "ITEM_MAX_REPEL" : "",
    "ITEM_ESCAPE_ROPE" : "",
    "ITEM_REPEL" : "",
    "ITEM_LINK_CABLE" : "",
    "ITEM_PROTECTOR" : "Protector",
    "ITEM_ELECTIRIZER" : "Electirizer",
    "ITEM_MAGMARIZER" : "Magmarizer",
    "ITEM_DUBIOUS_DISC" : "Dubious Disc",
    "ITEM_REAPER_CLOTH" : "Reaper Cloth",
    "ITEM_SUN_STONE" : "Sun Stone",
    "ITEM_MOON_STONE" : "Moon Stone",
    "ITEM_FIRE_STONE" : "Fire Stone",
    "ITEM_THUNDER_STONE" : "Thunder Stone",
    "ITEM_WATER_STONE" : "Water Stone",
    "ITEM_LEAF_STONE" : "Leaf Stone",
    "ITEM_SHINY_STONE" : "Shiny Stone",
    "ITEM_DUSK_STONE" : "Dusk Stone",
    "ITEM_DAWN_STONE" : "Dawn Stone",
    "ITEM_ICE_STONE" : "Ice Stone",
    "ITEM_TINY_MUSHROOM" : "",
    "ITEM_BIG_MUSHROOM" : "",
    "ITEM_BALM_MUSHROOM" : "",
    "ITEM_PEARL" : "",
    "ITEM_BIG_PEARL" : "",
    "ITEM_STARDUST" : "",
    "ITEM_STAR_PIECE" : "",
    "ITEM_NUGGET" : "",
    "ITEM_HEART_SCALE" : "",
    "ITEM_RARE_BONE" : "",
    "ITEM_PEARL_STRING" : "",
    "ITEM_COMET_SHARD" : "",
    "ITEM_BIG_NUGGET" : "",
    "ITEM_HONEY" : "",
    "ITEM_PRETTY_WING" : "",
    "ITEM_OVAL_STONE" : "Oval Stone",
    "ITEM_RAZOR_CLAW" : "Razor Claw",
    "ITEM_RAZOR_FANG" : "Razor Fang",
    "ITEM_ORANGE_MAIL" : "Mail",
    "ITEM_HARBOR_MAIL" : "Mail",
    "ITEM_GLITTER_MAIL" : "Mail",
    "ITEM_MECH_MAIL" : "Mail",
    "ITEM_WOOD_MAIL" : "Mail",
    "ITEM_WAVE_MAIL" : "Mail",
    "ITEM_BEAD_MAIL" : "Mail",
    "ITEM_SHADOW_MAIL" : "Mail",
    "ITEM_TROPIC_MAIL" : "Mail",
    "ITEM_DREAM_MAIL" : "Mail",
    "ITEM_FAB_MAIL" : "Mail",
    "ITEM_RETRO_MAIL" : "Mail",
    "ITEM_CHERI_BERRY" : "Cheri Berry",
    "ITEM_CHESTO_BERRY" : "Chesto Berry",
    "ITEM_PECHA_BERRY" : "Pecha Berry",
    "ITEM_RAWST_BERRY" : "Rawst Berry",
    "ITEM_ASPEAR_BERRY" : "Aspear Berry",
    "ITEM_LEPPA_BERRY" : "Leppa Berry",
    "ITEM_ORAN_BERRY" : "Oran Berry",
    "ITEM_PERSIM_BERRY" : "Persim Berry",
    "ITEM_LUM_BERRY" : "Lum Berry",
    "ITEM_SITRUS_BERRY" : "Sitrus Berry",
    "ITEM_FIGY_BERRY" : "Figy Berry",
    "ITEM_WIKI_BERRY" : "Wiki Berry",
    "ITEM_MAGO_BERRY" : "Mago Berry",
    "ITEM_AGUAV_BERRY" : "Aguav Berry",
    "ITEM_IAPAPA_BERRY" : "Iapapa Berry",
    "ITEM_RAZZ_BERRY" : "Razz Berry",
    "ITEM_BLUK_BERRY" : "Bluk Berry",
    "ITEM_NANAB_BERRY" : "Nanab Berry",
    "ITEM_WEPEAR_BERRY" : "Wepear Berry",
    "ITEM_PINAP_BERRY" : "Pinap Berry",
    "ITEM_POMEG_BERRY" : "Pomeg Berry",
    "ITEM_KELPSY_BERRY" : "Kelpsy Berry",
    "ITEM_QUALOT_BERRY" : "Qualot Berry",
    "ITEM_HONDEW_BERRY" : "Hondew Berry",
    "ITEM_GREPA_BERRY" : "Grepa Berry",
    "ITEM_TAMATO_BERRY" : "Tamato Berry",
    "ITEM_CORNN_BERRY" : "Cornn Berry",
    "ITEM_MAGOST_BERRY" : "Magost Berry",
    "ITEM_RABUTA_BERRY" : "Rabuta Berry",
    "ITEM_NOMEL_BERRY" : "Nomel Berry",
    "ITEM_SPELON_BERRY" : "Spelon Berry",
    "ITEM_PAMTRE_BERRY" : "Pamtre Berry",
    "ITEM_WATMEL_BERRY" : "Watmel Berry",
    "ITEM_DURIN_BERRY" : "Durin Berry",
    "ITEM_BELUE_BERRY" : "Belue Berry",
    "ITEM_LIECHI_BERRY" : "Liechi Berry",
    "ITEM_GANLON_BERRY" : "Ganlon Berry",
    "ITEM_SALAC_BERRY" : "Salac Berry",
    "ITEM_PETAYA_BERRY" : "Petaya Berry",
    "ITEM_APICOT_BERRY" : "Apicot Berry",
    "ITEM_LANSAT_BERRY" : "Lansat Berry",
    "ITEM_STARF_BERRY" : "Starf Berry",
    "ITEM_ENIGMA_BERRY_OLD" : "Enigma Berry",
    "ITEM_ENIGMA_BERRY" : "Enigma Berry",
    "ITEM_PRISM_SCALE" : "Prism Scale",
    "ITEM_SACHET" : "Sachet",
    "ITEM_WHIPPED_DREAM" : "Whipped Dream",
    "ITEM_BRIGHT_POWDER" : "Bright Powder",
    "ITEM_WHITE_HERB" : "White Herb",
    "ITEM_MACHO_BRACE" : "Macho Brace",
    "ITEM_EXP_SHARE" : "",
    "ITEM_QUICK_CLAW" : "Quick Claw",
    "ITEM_SOOTHE_BELL" : "",
    "ITEM_MENTAL_HERB" : "Mental Herb",
    "ITEM_CHOICE_BAND" : "Choice Band",
    "ITEM_KINGS_ROCK" : "King\s Rock",
    "ITEM_SILVER_POWDER" : "Silver Powder",
    "ITEM_AMULET_COIN" : "Metal Coat",
    "ITEM_CLEANSE_TAG" : "Lax Incense",
    "ITEM_SOUL_DEW" : "Soul Dew",
    "ITEM_DEEP_SEA_TOOTH" : "Deep Sea Tooth",
    "ITEM_DEEP_SEA_SCALE" : "Deep Sea Scale",
    "ITEM_SMOKE_BALL" : "",
    "ITEM_EVERSTONE" : "",
    "ITEM_FOCUS_BAND" : "Focus Band",
    "ITEM_LUCKY_EGG" : "",
    "ITEM_SCOPE_LENS" : "Scope Lens",
    "ITEM_METAL_COAT" : "Metal Coat",
    "ITEM_LEFTOVERS" : "Leftovers",
    "ITEM_DRAGON_SCALE" : "Dragon Scale",
    "ITEM_LIGHT_BALL" : "Light Ball",
    "ITEM_SOFT_SAND" : "Soft Sand",
    "ITEM_HARD_STONE" : "Hard Stone",
    "ITEM_MIRACLE_SEED" : "Miracle Seed",
    "ITEM_BLACK_GLASSES" : "Black Glasses",
    "ITEM_BLACK_BELT" : "Black Belt",
    "ITEM_MAGNET" : "Magnet",
    "ITEM_MYSTIC_WATER" : "Mystic Water",
    "ITEM_SHARP_BEAK" : "Sharp Beak",
    "ITEM_POISON_BARB" : "Poison Barb",
    "ITEM_NEVER_MELT_ICE" : "Never-Melt Ice",
    "ITEM_SPELL_TAG" : "Spell Tag",
    "ITEM_TWISTED_SPOON" : "Twisted Spoon",
    "ITEM_CHARCOAL" : "Charcoal",
    "ITEM_DRAGON_FANG" : "Dragon Fang",
    "ITEM_SILK_SCARF" : "Silk Scarf",
    "ITEM_UP_GRADE" : "Up-Grade",
    "ITEM_SHELL_BELL" : "Shell Bell",
    "ITEM_SEA_INCENSE" : "Sea Incense",
    "ITEM_LAX_INCENSE" : "Lax Incense",
    "ITEM_LUCKY_PUNCH" : "Lucky Punch",
    "ITEM_METAL_POWDER" : "Metal Powder",
    "ITEM_THICK_CLUB" : "Thick Club",
    "ITEM_LEEK" : "Leek",
    "ITEM_STRAWBERRY_SWEET" : "Strawberry Sweet",
    "ITEM_BERRY_SWEET" : "Berry Sweet",
    "ITEM_LOVE_SWEET" : "Love Sweet",
    "ITEM_CLOVER_SWEET" : "Clover Sweet",
    "ITEM_FLOWER_SWEET" : "Flower Sweet",
    "ITEM_RIBBON_SWEET" : "Ribbon Sweet",
    "ITEM_STAR_SWEET" : "Star Sweet",
    "ITEM_SWEET_APPLE" : "Sweet Apple",
    "ITEM_TART_APPLE" : "Tart Apple",
    "ITEM_CRACKED_POT" : "Cracked Pot",
    "ITEM_CHIPPED_POT" : "Chipped Pot",
    "ITEM_GALARICA_CUFF" : "Galarica Cuff",
    "ITEM_GALARICA_CROWN" : "Galarica Wreath",
    "ITEM_CHERISH_BALL" : "Cherish Ball",
    "ITEM_DUSK_BALL" : "Dusk Ball",
    "ITEM_HEAL_BALL" : "Heal Ball",
    "ITEM_QUICK_BALL" : "Quick Ball",
    "ITEM_FAST_BALL" : "Fast Ball",
    "ITEM_LEVEL_BALL" : "Level Ball",
    "ITEM_LURE_BALL" : "Lure Ball",
    "ITEM_HEAVY_BALL" : "Heavy Ball",
    "ITEM_LOVE_BALL" : "Love Ball",
    "ITEM_FRIEND_BALL" : "Friend Ball",
    "ITEM_MOON_BALL" : "Moon Ball",
    "ITEM_SPORT_BALL" : "Sport Ball",
    "ITEM_BEAST_BALL" : "Beast Ball",
    "ITEM_DREAM_BALL" : "Dream Ball",
    "ITEM_PARK_BALL" : "Park Ball",
    "ITEM_RED_SCARF" : "",
    "ITEM_BLUE_SCARF" : "",
    "ITEM_PINK_SCARF" : "",
    "ITEM_GREEN_SCARF" : "",
    "ITEM_YELLOW_SCARF" : "",
    "ITEM_MACH_BIKE" : "",
    "ITEM_COIN_CASE" : "",
    "ITEM_ITEMFINDER" : "",
    "ITEM_OLD_ROD" : "",
    "ITEM_GOOD_ROD" : "",
    "ITEM_SUPER_ROD" : "",
    "ITEM_SS_TICKET" : "",
    "ITEM_CONTEST_PASS" : "",
    "ITEM_Z_POWER_RING" : "",
    "ITEM_WAILMER_PAIL" : "",
    "ITEM_DEVON_GOODS" : "",
    "ITEM_SOOT_SACK" : "",
    "ITEM_BASEMENT_KEY" : "",
    "ITEM_ACRO_BIKE" : "",
    "ITEM_POKEBLOCK_CASE" : "",
    "ITEM_LETTER" : "",
    "ITEM_EON_TICKET" : "",
    "ITEM_RED_ORB" : "Red Orb",
    "ITEM_BLUE_ORB" : "Blue Orb",
    "ITEM_SCANNER" : "",
    "ITEM_GO_GOGGLES" : "",
    "ITEM_METEORITE" : "",
    "ITEM_ROOM_1_KEY" : "",
    "ITEM_ROOM_2_KEY" : "",
    "ITEM_ROOM_4_KEY" : "",
    "ITEM_ROOM_6_KEY" : "",
    "ITEM_STORAGE_KEY" : "",
    "ITEM_ROOT_FOSSIL" : "Root Fossil",
    "ITEM_CLAW_FOSSIL" : "Claw Fossil",
    "ITEM_DEVON_SCOPE" : "",
    "ITEM_TM01_FOCUS_PUNCH" : "",
    "ITEM_TM02_DRAGON_CLAW" : "",
    "ITEM_TM03_WATER_PULSE" : "",
    "ITEM_TM04_CALM_MIND" : "",
    "ITEM_TM05_ROAR" : "",
    "ITEM_TM06_TOXIC" : "",
    "ITEM_TM07_HAIL" : "",
    "ITEM_TM08_BULK_UP" : "",
    "ITEM_TM09_BULLET_SEED" : "",
    "ITEM_TM10_HIDDEN_POWER" : "",
    "ITEM_TM11_SUNNY_DAY" : "",
    "ITEM_TM12_TAUNT" : "",
    "ITEM_TM13_ICE_BEAM" : "",
    "ITEM_TM14_BLIZZARD" : "",
    "ITEM_TM15_HYPER_BEAM" : "",
    "ITEM_TM16_LIGHT_SCREEN" : "",
    "ITEM_TM17_PROTECT" : "",
    "ITEM_TM18_RAIN_DANCE" : "",
    "ITEM_TM19_GIGA_DRAIN" : "",
    "ITEM_TM20_SAFEGUARD" : "",
    "ITEM_TM21_FRUSTRATION" : "",
    "ITEM_TM22_SOLARBEAM" : "",
    "ITEM_TM23_IRON_TAIL" : "",
    "ITEM_TM24_THUNDERBOLT" : "",
    "ITEM_TM25_THUNDER" : "",
    "ITEM_TM26_EARTHQUAKE" : "",
    "ITEM_TM27_RETURN" : "",
    "ITEM_TM28_DIG" : "",
    "ITEM_TM29_PSYCHIC" : "",
    "ITEM_TM30_SHADOW_BALL" : "",
    "ITEM_TM31_BRICK_BREAK" : "",
    "ITEM_TM32_DOUBLE_TEAM" : "",
    "ITEM_TM33_REFLECT" : "",
    "ITEM_TM34_SHOCK_WAVE" : "",
    "ITEM_TM35_FLAMETHROWER" : "",
    "ITEM_TM36_SLUDGE_BOMB" : "",
    "ITEM_TM37_SANDSTORM" : "",
    "ITEM_TM38_FIRE_BLAST" : "",
    "ITEM_TM39_ROCK_TOMB" : "",
    "ITEM_TM40_AERIAL_ACE" : "",
    "ITEM_TM41_TORMENT" : "",
    "ITEM_TM42_FACADE" : "",
    "ITEM_TM43_SECRET_POWER" : "",
    "ITEM_TM44_REST" : "",
    "ITEM_TM45_ATTRACT" : "",
    "ITEM_TM46_THIEF" : "",
    "ITEM_TM47_STEEL_WING" : "",
    "ITEM_TM48_SKILL_SWAP" : "",
    "ITEM_TM49_SNATCH" : "",
    "ITEM_TM50_OVERHEAT" : "",
    "ITEM_HM01_CUT" : "",
    "ITEM_HM02_FLY" : "",
    "ITEM_HM03_SURF" : "",
    "ITEM_HM04_STRENGTH" : "",
    "ITEM_HM05_FLASH" : "",
    "ITEM_HM06_ROCK_SMASH" : "",
    "ITEM_HM07_WATERFALL" : "",
    "ITEM_HM08_ROCK_CLIMB" : "",
    "ITEM_TM51" : "",
    "ITEM_TM52" : "",
    "ITEM_TM53" : "",
    "ITEM_TM54" : "",
    "ITEM_TM55" : "",
    "ITEM_TM56" : "",
    "ITEM_TM57" : "",
    "ITEM_TM58" : "",
    "ITEM_TM59_DRAGON_PULSE" : "",
    "ITEM_TM60_DRAIN_PUNCH" : "",
    "ITEM_TM61_WILL_O_WISP" : "",
    "ITEM_TM62_SILVER_WIND" : "",
    "ITEM_TM63_VENOSHOCK" : "",
    "ITEM_TM64_EXPLOSION" : "",
    "ITEM_TM65_SHADOW_CLAW" : "",
    "ITEM_TM66_PAYBACK" : "",
    "ITEM_TM67_RECYCLE" : "",
    "ITEM_TM68_GIGA_IMPACT" : "",
    "ITEM_TM69_ROCK_POLISH" : "",
    "ITEM_TM70_FLASH" : "",
    "ITEM_TM71_STONE_EDGE" : "",
    "ITEM_TM72_AVALANCHE" : "",
    "ITEM_TM73_THUNDER_WAVE" : "",
    "ITEM_TM74_GYRO_BALL" : "",
    "ITEM_TM75_SWORDS_DANCE" : "",
    "ITEM_TM76_STEALTH_ROCK" : "",
    "ITEM_TM77_FLAME_CHARGE" : "",
    "ITEM_TM78_LOW_SWEEP" : "",
    "ITEM_TM79_DARK_PULSE" : "",
    "ITEM_TM80_ROCK_SLIDE" : "",
    "ITEM_TM81_X_SCISSOR" : "",
    "ITEM_TM82_SLEEP_TALK" : "",
    "ITEM_TM83_SCALD" : "",
    "ITEM_TM84_POISON_JAB" : "",
    "ITEM_TM85_DREAM_EATER" : "",
    "ITEM_TM86_GRASS_KNOT" : "",
    "ITEM_TM87_SWAGGER" : "",
    "ITEM_TM88_PLUCK" : "",
    "ITEM_TM89_U_TURN" : "",
    "ITEM_TM90_SUBSTITUTE" : "",
    "ITEM_TM91_FLASH_CANNON" : "",
    "ITEM_TM92_VOLT_SWITCH" : "",
    "ITEM_TM93_DRAGON_TAIL" : "",
    "ITEM_TM94_INCINERATE" : "",
    "ITEM_TM95_STRUGGLE_BUG" : "",
    "ITEM_TM96_BULLDOZE" : "",
    "ITEM_TM97_FROST_BREATH" : "",
    "ITEM_TM98_WORK_UP" : "",
    "ITEM_TM99_WILD_CHARGE" : "",
    "ITEM_TM100_INFESTATION" : "",
    "ITEM_TM101_POWER_UP_PUNCH" : "",
    "ITEM_TM102_DAZZLING_GLEAM" : "",
    "ITEM_TM103_SLUDGE_WAVE" : "",
    "ITEM_TM104_PSYSHOCK" : "",
    "ITEM_TM105_BRUTAL_SWING" : "",
    "ITEM_TM106_SMART_STRIKE" : "",
    "ITEM_TM107_ACROBATICS" : "",
    "ITEM_TM108_SNARL" : "",
    "ITEM_TM109_DEFOG" : "",
    "ITEM_TM110_CAPTIVATE" : "",
    "ITEM_TM111_SMACK_DOWN" : "",
    "ITEM_TM112_ROUND" : "",
    "ITEM_TM113_ECHOED_VOICE" : "",
    "ITEM_TM114_NATURAL_GIFT" : "",
    "ITEM_TM115_QUASH" : "",
    "ITEM_TM116_TRICK_ROOM" : "",
    "ITEM_TM117_FLING" : "",
    "ITEM_TM118_AURORA_VEIL" : "",
    "ITEM_TM119_SKY_DROP" : "",
    "ITEM_TM120_NATURE_POWER" : "",
    "ITEM_DYNAMAX_BAND" : "",
    "ITEM_GOLD_TEETH" : "",
    "ITEM_OAKS_PARCEL" : "",
    "ITEM_POKE_FLUTE" : "",
    "ITEM_SECRET_KEY" : "",
    "ITEM_BIKE_VOUCHER" : "",
    "ITEM_MEGA_RING" : "",
    "ITEM_OLD_AMBER" : "Old Amber",
    "ITEM_CARD_KEY" : "",
    "ITEM_LIFT_KEY" : "",
    "ITEM_HELIX_FOSSIL" : "Helix Fossil",
    "ITEM_DOME_FOSSIL" : "Dome Fossil",
    "ITEM_SILPH_SCOPE" : "",
    "ITEM_BICYCLE" : "",
    "ITEM_TOWN_MAP" : "",
    "ITEM_VS_SEEKER" : "",
    "ITEM_FAME_CHECKER" : "",
    "ITEM_TM_CASE" : "",
    "ITEM_BERRY_POUCH" : "",
    "ITEM_TEACHY_TV" : "",
    "ITEM_TRI_PASS" : "",
    "ITEM_RAINBOW_PASS" : "",
    "ITEM_TEA" : "",
    "ITEM_MYSTIC_TICKET" : "",
    "ITEM_AURORA_TICKET" : "",
    "ITEM_POWDER_JAR" : "",
    "ITEM_RUBY" : "",
    "ITEM_SAPPHIRE" : "",
    "ITEM_X_SP_DEF" : "",
    "ITEM_OCCA_BERRY" : "Occa Berry",
    "ITEM_PASSHO_BERRY" : "Passho Berry",
    "ITEM_WACAN_BERRY" : "Wacan Berry",
    "ITEM_RINDO_BERRY" : "Rindo Berry",
    "ITEM_YACHE_BERRY" : "Yache Berry",
    "ITEM_CHOPLE_BERRY" : "Chople Berry",
    "ITEM_KEBIA_BERRY" : "Kebia Berry",
    "ITEM_SHUCA_BERRY" : "Shuca Berry",
    "ITEM_COBA_BERRY" : "Coba Berry",
    "ITEM_PAYAPA_BERRY" : "Payapa Berry",
    "ITEM_TANGA_BERRY" : "Tanga Berry",
    "ITEM_CHARTI_BERRY" : "Charti Berry",
    "ITEM_KASIB_BERRY" : "Kasib Berry",
    "ITEM_HABAN_BERRY" : "Haban Berry",
    "ITEM_COLBUR_BERRY" : "Colbur Berry",
    "ITEM_BABIRI_BERRY" : "Babiri Berry",
    "ITEM_CHILAN_BERRY" : "Chilan Berry",
    "ITEM_MICLE_BERRY" : "Micle Berry",
    "ITEM_CUSTAP_BERRY" : "Custap Berry",
    "ITEM_JABOCA_BERRY" : "Jaboca Berry",
    "ITEM_ROWAP_BERRY" : "Rowap Berry",
    "ITEM_ROSELI_BERRY" : "Roseli Berry",
    "ITEM_KEE_BERRY" : "Kee Berry",
    "ITEM_MARANGA_BERRY" : "Maranga Berry",
    "ITEM_OVAL_CHARM" : "",
    "ITEM_SHINY_CHARM" : "",
    "ITEM_RAINBOW_WING" : "",
    "ITEM_SILVER_WING" : "",
    "ITEM_MAGMA_STONE" : "",
    "ITEM_LIGHT_STONE" : "",
    "ITEM_DARK_STONE" : "",
    "ITEM_SUN_FLUTE" : "",
    "ITEM_MOON_FLUTE" : "",
    "ITEM_GRACIDEA" : "",
    "ITEM_DNA_SPLICERS" : "",
    "ITEM_REVEAL_GLASS" : "",
    "ITEM_PRISON_BOTTLE" : "",
    "ITEM_N_SOLARIZER" : "",
    "ITEM_N_LUNARIZER" : "",
    "ITEM_RUSTED_SWORD" : "Rusted Sword",
    "ITEM_RUSTED_SHIELD" : "Rusted Shield",
    "ITEM_ADAMANT_ORB" : "Adamant Orb",
    "ITEM_LUSTROUS_ORB" : "Lustrous Orb",
    "ITEM_GRISEOUS_ORB" : "Griseous Orb",
    "ITEM_FIST_PLATE" : "Fist Plate",
    "ITEM_SKY_PLATE" : "Sky Plate",
    "ITEM_TOXIC_PLATE" : "Toxic Plate",
    "ITEM_EARTH_PLATE" : "Earth Plate",
    "ITEM_STONE_PLATE" : "Stone Plate",
    "ITEM_INSECT_PLATE" : "Insect Plate",
    "ITEM_SPOOKY_PLATE" : "Spooky Plate",
    "ITEM_IRON_PLATE" : "Iron Plate",
    "ITEM_FLAME_PLATE" : "Flame Plate",
    "ITEM_SPLASH_PLATE" : "Splash Plate",
    "ITEM_MEADOW_PLATE" : "Meadow Plate",
    "ITEM_ZAP_PLATE" : "Zap Plate",
    "ITEM_MIND_PLATE" : "Mind Plate",
    "ITEM_ICICLE_PLATE" : "Icicle Plate",
    "ITEM_DRACO_PLATE" : "Draco Plate",
    "ITEM_DREAD_PLATE" : "Dread Plate",
    "ITEM_PIXIE_PLATE" : "Pixie Plate",
    "ITEM_FIGHTING_MEMORY" : "Fighting Memory",
    "ITEM_FLYING_MEMORY" : "Flying Memory",
    "ITEM_POISON_MEMORY" : "Poison Memory",
    "ITEM_GROUND_MEMORY" : "Ground Memory",
    "ITEM_ROCK_MEMORY" : "Rock Memory",
    "ITEM_BUG_MEMORY" : "Bug Memory",
    "ITEM_GHOST_MEMORY" : "Ghost Memory",
    "ITEM_STEEL_MEMORY" : "Steel Memory",
    "ITEM_FIRE_MEMORY" : "Fire Memory",
    "ITEM_WATER_MEMORY" : "Water Memory",
    "ITEM_GRASS_MEMORY" : "Grass Memory",
    "ITEM_ELECTRIC_MEMORY" : "Electric Memory",
    "ITEM_PSYCHIC_MEMORY" : "Psychic Memory",
    "ITEM_ICE_MEMORY" : "Ice Memory",
    "ITEM_DRAGON_MEMORY" : "Dragon Memory",
    "ITEM_DARK_MEMORY" : "Dark Memory",
    "ITEM_FAIRY_MEMORY" : "Fairy Memory",
    "ITEM_BURN_DRIVE" : "Burn Drive",
    "ITEM_DOUSE_DRIVE" : "Douse Drive",
    "ITEM_SHOCK_DRIVE" : "Shock Drive",
    "ITEM_CHILL_DRIVE" : "Chill Drive",
    "ITEM_RED_NECTAR" : "",
    "ITEM_YELLOW_NECTAR" : "",
    "ITEM_PINK_NECTAR" : "",
    "ITEM_PURPLE_NECTAR" : "",
    "ITEM_ULTRANECROZIUM_Z": "Ultranecrozium Z",
    "ITEM_VENUSAURITE" : "Venusaurite",
    "ITEM_CHARIZARDITE_X" : "Charizardite X",
    "ITEM_CHARIZARDITE_Y" : "Charizardite Y",
    "ITEM_BLASTOISINITE" : "Blastoisinite",
    "ITEM_BEEDRILLITE" : "Beedrillite",
    "ITEM_PIDGEOTITE" : "Pidgeotite",
    "ITEM_ALAKAZITE" : "Alakazite",
    "ITEM_SLOWBRONITE" : "Slowbronite",
    "ITEM_GENGARITE" : "Gengarite",
    "ITEM_KANGASKHANITE" : "Kangaskhanite",
    "ITEM_PINSIRITE" : "Pinsirite",
    "ITEM_GYARADOSITE" : "Gyaradosite",
    "ITEM_AERODACTYLITE" : "Aerodactylite",
    "ITEM_MEWTWONITE_X" : "Mewtwonite X",
    "ITEM_MEWTWONITE_Y" : "Mewtwonite Y",
    "ITEM_AMPHAROSITE" : "Ampharosite",
    "ITEM_STEELIXITE" : "Steelixite",
    "ITEM_SCIZORITE" : "Scizorite",
    "ITEM_HERACRONITE" : "Heracronite",
    "ITEM_HOUNDOOMINITE" : "Houndoominite",
    "ITEM_TYRANITARITE" : "Tyranitarite",
    "ITEM_SCEPTILITE" : "Sceptilite",
    "ITEM_BLAZIKENITE" : "Blazikenite",
    "ITEM_SWAMPERTITE" : "Swampertite",
    "ITEM_GARDEVOIRITE" : "Gardevoirite",
    "ITEM_SABLENITE" : "Sablenite",
    "ITEM_MAWILITE" : "Mawilite",
    "ITEM_AGGRONITE" : "Aggronite",
    "ITEM_MEDICHAMITE" : "Medichamite",
    "ITEM_MANECTITE" : "Manectite",
    "ITEM_SHARPEDONITE" : "Sharpedonite",
    "ITEM_CAMERUPTITE" : "Cameruptite",
    "ITEM_ALTARIANITE" : "Altarianite",
    "ITEM_BANETTITE" : "Banettite",
    "ITEM_ABSOLITE" : "Absolite",
    "ITEM_GLALITITE" : "Glalitite",
    "ITEM_SALAMENCITE" : "Salamencite",
    "ITEM_METAGROSSITE" : "Metagrossite",
    "ITEM_LATIASITE" : "Latiasite",
    "ITEM_LATIOSITE" : "Latiosite",
    "ITEM_LOPUNNITE" : "Lopunnite",
    "ITEM_GARCHOMPITE" : "Garchompite",
    "ITEM_LUCARIONITE" : "Lucarionite",
    "ITEM_ABOMASITE" : "Abomasite",
    "ITEM_GALLADITE" : "Galladite",
    "ITEM_AUDINITE" : "Audinite",
    "ITEM_DIANCITE" : "Diancite",
    "ITEM_MACHAMPITE" : "Machampite",
    "ITEM_LAPRASITE" : "Laprasite",
    "ITEM_BUTTERFRITE" : "Butterfrite",
    "ITEM_GARBODORITE" : "Garbodorite",
    "ITEM_SNORLAXITE" : "Snorlaxite",
    "ITEM_KINGLERITE" : "Kinglerite",
    "ITEM_TOXTRICITITE" : "Toxtricitite",
    "ITEM_COALOSSITE" : "Coalossite",
    "ITEM_DURALUDONITE" : "Duraludonite",
    "ITEM_DREDNAWITE" : "Drednawite",
    "ITEM_COPPERAJITE" : "Copperajite",
    "ITEM_APPLITE" : "Flapplite",
    "ITEM_ORBEETLITE" : "Orbeetlite",
    "ITEM_GRIMMSNITE" : "",
    "ITEM_CENTISKITE" : "Centiskite",
    "ITEM_SANDACONDITE" : "Sandacondite",
    "ITEM_ALCREMITE" : "Alcremite",
    "ITEM_ETERNAMAX_ORB" : "Eternamax Orb",
    "ITEM_NORMALIUM_Z" : "Normalium Z",
    "ITEM_FIGHTINIUM_Z" : "Fightinium Z",
    "ITEM_FLYINIUM_Z" : "Flyinium Z",
    "ITEM_POISONIUM_Z" : "Poisonium Z",
    "ITEM_GROUNDIUM_Z" : "Groundium Z",
    "ITEM_ROCKIUM_Z" : "Rockium Z",
    "ITEM_BUGINIUM_Z" : "Buginium Z",
    "ITEM_GHOSTIUM_Z" : "Ghostium Z",
    "ITEM_STEELIUM_Z" : "Steelium Z",
    "ITEM_FIRIUM_Z" : "Firium Z",
    "ITEM_WATERIUM_Z" : "Waterium Z",
    "ITEM_GRASSIUM_Z" : "Grassium Z",
    "ITEM_ELECTRIUM_Z" : "Electrium Z",
    "ITEM_PSYCHIUM_Z" : "Psychium Z",
    "ITEM_ICIUM_Z" : "Icium Z",
    "ITEM_DRAGONIUM_Z" : "Dragonium Z",
    "ITEM_DARKINIUM_Z" : "Darkinium Z",
    "ITEM_FAIRIUM_Z" : "Fairium Z",
    "ITEM_ALORAICHIUM_Z" : "Aloraichium Z",
    "ITEM_DECIDIUM_Z" : "Decidium Z",
    "ITEM_EEVIUM_Z" : "Eevium Z",
    "ITEM_INCINIUM_Z" : "Incinium Z",
    "ITEM_KOMMONIUM_Z" : "Kommonium Z",
    "ITEM_LUNALIUM_Z" : "Lunalium Z",
    "ITEM_LYCANIUM_Z" : "Lycanium Z",
    "ITEM_MARSHADIUM_Z" : "Marshadium Z",
    "ITEM_MEWNIUM_Z" : "Mewnium Z",
    "ITEM_MIMIKIUM_Z" : "Mimikium Z",
    "ITEM_PIKANIUM_Z" : "Pikanium Z",
    "ITEM_PIKASHUNIUM_Z" : "Pikashunium Z",
    "ITEM_PRIMARIUM_Z" : "Primarium Z",
    "ITEM_SNORLIUM_Z" : "Snorlium Z",
    "ITEM_SOLGANIUM_Z" : "Solganium Z",
    "ITEM_TAPUNIUM_Z" : "Tapunium Z",
    "ITEM_BLACK_APRICORN" : "",
    "ITEM_BLUE_APRICORN" : "",
    "ITEM_GREEN_APRICORN" : "",
    "ITEM_PINK_APRICORN" : "",
    "ITEM_RED_APRICORN" : "",
    "ITEM_WHITE_APRICORN" : "",
    "ITEM_YELLOW_APRICORN" : "",
    "ITEM_RELIC_COPPER" : "",
    "ITEM_RELIC_SILVER" : "",
    "ITEM_RELIC_GOLD" : "",
    "ITEM_RELIC_VASE" : "",
    "ITEM_RELIC_BAND" : "",
    "ITEM_RELIC_STATUE" : "",
    "ITEM_RELIC_CROWN" : "",
    "ITEM_SKULL_FOSSIL" : "Skull Fossil",
    "ITEM_ARMOR_FOSSIL" : "Armor Fossil",
    "ITEM_COVER_FOSSIL" : "Cover Fossil",
    "ITEM_PLUME_FOSSIL" : "Plume Fossil",
    "ITEM_JAW_FOSSIL" : "Jaw Fossil",
    "ITEM_SAIL_FOSSIL" : "Sail Fossil",
    "ITEM_FOSSILIZED_BIRD" : "Fossilized Bird",
    "ITEM_FOSSILIZED_FISH" : "Fossilized Fish",
    "ITEM_FOSSILIZED_DRAKE" : "Fossilized Drake",
    "ITEM_FOSSILIZED_DINO" : "Fossilized Dino",
    "ITEM_ODD_KEYSTONE" : "",
    "ITEM_BOTTLE_CAP" : "Bottle Cap",
    "ITEM_GOLD_BOTTLE_CAP" : "Gold Bottle Cap",
    "ITEM_WISHING_PIECE" : "",
    "ITEM_ABILITY_CAPSULE" : "",
    "ITEM_POWER_BRACER" : "Power Bracer",
    "ITEM_POWER_BELT" : "Power Belt",
    "ITEM_POWER_LENS" : "Power Lens",
    "ITEM_POWER_BAND" : "Power Band",
    "ITEM_POWER_ANKLET" : "Power Anklet",
    "ITEM_POWER_WEIGHT" : "Power Weight",
    "ITEM_LUCK_INCENSE" : "",
    "ITEM_FULL_INCENSE" : "Full Incense",
    "ITEM_ODD_INCENSE" : "Odd Incense",
    "ITEM_PURE_INCENSE" : "",
    "ITEM_ROCK_INCENSE" : "Rock Incense",
    "ITEM_ROSE_INCENSE" : "Rose Incense",
    "ITEM_WAVE_INCENSE" : "Wave Incense",
    "ITEM_NORMAL_GEM" : "Normal Gem",
    "ITEM_FIGHTING_GEM" : "Fighting Gem",
    "ITEM_FLYING_GEM" : "Flying Gem",
    "ITEM_POISON_GEM" : "Poison Gem",
    "ITEM_GROUND_GEM" : "Ground Gem",
    "ITEM_ROCK_GEM" : "Rock Gem",
    "ITEM_BUG_GEM" : "Bug Gem",
    "ITEM_GHOST_GEM" : "Ghost Gem",
    "ITEM_STEEL_GEM" : "Steel Gem",
    "ITEM_FIRE_GEM" : "Fire Gem",
    "ITEM_WATER_GEM" : "Water Gem",
    "ITEM_GRASS_GEM" : "Grass Gem",
    "ITEM_ELECTRIC_GEM" : "Electric Gem",
    "ITEM_PSYCHIC_GEM" : "Psychic Gem",
    "ITEM_ICE_GEM" : "Ice Gem",
    "ITEM_DRAGON_GEM" : "Dragon Gem",
    "ITEM_DARK_GEM" : "Dark Gem",
    "ITEM_FAIRY_GEM" : "Fairy Gem",
    "ITEM_WIDE_LENS" : "Wide Lens",
    "ITEM_MUSCLE_BAND" : "Muscle Band",
    "ITEM_WISE_GLASSES" : "Wise Glasses",
    "ITEM_EXPERT_BELT" : "Expert Belt",
    "ITEM_LIGHT_CLAY" : "Light Clay",
    "ITEM_LIFE_ORB" : "Life Orb",
    "ITEM_POWER_HERB" : "Power Herb",
    "ITEM_TOXIC_ORB" : "Toxic Orb",
    "ITEM_FLAME_ORB" : "Flame Orb",
    "ITEM_QUICK_POWDER" : "Quick Powder",
    "ITEM_FOCUS_SASH" : "Focus Sash",
    "ITEM_ZOOM_LENS" : "Zoom Lens",
    "ITEM_METRONOME" : "Metronome",
    "ITEM_IRON_BALL" : "Iron Ball",
    "ITEM_LAGGING_TAIL" : "Lagging Tail",
    "ITEM_DESTINY_KNOT" : "Destiny Knot",
    "ITEM_BLACK_SLUDGE" : "Black Sludge",
    "ITEM_ICY_ROCK" : "Icy Rock",
    "ITEM_SMOOTH_ROCK" : "Smooth Rock",
    "ITEM_HEAT_ROCK" : "Heat Rock",
    "ITEM_DAMP_ROCK" : "Damp Rock",
    "ITEM_GRIP_CLAW" : "Grip Claw",
    "ITEM_CHOICE_SCARF" : "Choice Scarf",
    "ITEM_CHOICE_SPECS" : "Choice Specs",
    "ITEM_STICKY_BARB" : "Sticky Barb",
    "ITEM_SHED_SHELL" : "Shed Shell",
    "ITEM_BIG_ROOT" : "Big Root",
    "ITEM_EVIOLITE" : "Eviolite",
    "ITEM_FLOAT_STONE" : "Float Stone",
    "ITEM_ROCKY_HELMET" : "Rocky Helmet",
    "ITEM_AIR_BALLOON" : "Air Balloon",
    "ITEM_RED_CARD" : "Red Card",
    "ITEM_RING_TARGET" : "Ring Target",
    "ITEM_BINDING_BAND" : "Binding Band",
    "ITEM_ABSORB_BULB" : "Absorb Bulb",
    "ITEM_CELL_BATTERY" : "Cell Battery",
    "ITEM_EJECT_BUTTON" : "Eject Button",
    "ITEM_WEAKNESS_POLICY" : "Weakness Policy",
    "ITEM_ASSAULT_VEST" : "Assault Vest",
    "ITEM_LUMINOUS_MOSS" : "Luminous Moss",
    "ITEM_SNOWBALL" : "Snowball",
    "ITEM_SAFETY_GOGGLES" : "Safety Goggles",
    "ITEM_ADRENALINE_ORB" : "Adrenaline Orb",
    "ITEM_TERRAIN_EXTENDER" : "Terrain Extender",
    "ITEM_PROTECTIVE_PADS" : "Protective Pads",
    "ITEM_ELECTRIC_SEED" : "Electric Seed",
    "ITEM_GRASSY_SEED" : "Grassy Seed",
    "ITEM_MISTY_SEED" : "Misty Seed",
    "ITEM_PSYCHIC_SEED" : "Psychic Seed",
    "ITEM_EJECT_PACK" : "Eject Pack",
    "ITEM_ROOM_SERVICE" : "Room Service",
    "ITEM_BLUNDER_POLICY" : "Blunder Policy",
    "ITEM_HEAVY_DUTY_BOOTS" : "Heavy-Duty Boots",
    "ITEM_UTILITY_UMBRELLA" : "Utility Umbrella",
    "ITEM_THROAT_SPRAY" : "Throat Spray",
    "ITEM_MEDICINE" : "",
    "ITEM_FREE_SPACE19" : "",
    "ITEM_FREE_SPACE20" : "",
    "ITEM_FREE_SPACE21" : "",
    "ITEM_FREE_SPACE22" : "",
    }