namedict = {
    'Brendan Battle1' : "Brendan - Viridian Forest",
    'Route22 GarySquirtle' : "Gary - Route 22 [Squirtle]",
    'Route22 GaryBulbasaur' : "Gary - Route 22 [Bulbasaur]",
    'Route22 GaryCharmander' : "Gary - Route 22 [Charmander]",
    'ViridianBug Miniboss' : "Bug Catcher Sammy - Viridian Forest",
    'Falkner Battle1' : "Falkner - Pewter City",
    'Brock Battle1' : "Brock - Pewter Gym",
    'Route3 LassMiniBoss' : "Lass Sally - Route 3",
    'MtMoon Archer' : "Archer - Mt Moon",
    'MtMoon Scientist' : "Super Nerd Miguel - Mt Moon",
    'CeruleanGary Squirtle' : "Gary - Nugget Bridge [Squirtle]",
    'CeruleanGary Bulbasaur' : "Gary - Nugget Bridge [Bulbasaur]",
    'CeruleanGary Charmander' : "Gary - Nugget Bridge [Charmander]",
    'NuggetBridge Rocket' : "Nugget Grunt - Nugget Bridge",
    'Route24 Bugsy' : "Bugsy - Pre Surge - Route 25", 
    'Route24 BugsyPostSurge' : "Bugsy - Post Surge - Route 25", 
    'Misty1' : "Misty - Cerulean Gym",
    'Cerulean Rocket' : "Dig Grunt - Cerulean City",
    'Route6 Miniboss' : "Camper Jeff - Route 6",
    'Ssanne Trainer1' : "Gentleman Brroks - S.S Anne",
    'Ssanne Trainer2' : "Lass Anne - S.S Anne",
    'Ssanne Sailor1' : "Sailor Edmon - S.S Anne",
    'Ssanne Sailor2' : "Sailor Trevor - S.S Anne",
    'Brendan Battle2' : "Brendan 2 - S.S Anne",
    'Route11 Whitney' : "Whitney - Route 11", 
    'TwoIsland Whitney' : "Whitney Rematch - Two Island", 
    'TwoIsland AceT' : "Ace Trainer Andrew Post Game - Two Island", 
    'PkmnTower AceT1' : "Ace Trainer Runan  Post Game - Lavender Tower",
    'PkmnTower AceT2' : "Ace Trainer Samantha Post Game - Lavender Tower",
    'PkmnTower AceT3' : "Ace Trainer Symes Post Game - Lavender Tower",
    'PkmnTower Morty' : "Morty Rematch - Two Island",
    'Vermilion LtSurgeGymTrainer' : "Gentleman Tucker - Vermillion Gym",
    'Vermilion LtSurge' : " Lt. Surge - Vermillion Gym",
    'Route9 Cooltrainer' : "Picknicker Alicia - Route 9",
    'Route9 Cooltrainer2' : "Picnicker Caitlin - Route 9",
    'RockTunnel Cooltrainer' : "Picknicker Dana - Rock Tunnel",
    'Route10 Pokenerd' : "Pokenerd Herman - Route 10",
    'Route8 Pokenerd' : "Pokenerd Aiden - Route 8",
    'Celadon Erika1' : "Erika - Celadon City",
    'Lavender Morty' : "Morty - Lavender Town", 
    'GameCorner Rocket1' : "Team Rocket Grunt - Game Corner",
    'RocketHideout GruntMini1' : "Left Rocket Grunt - Hideout",
    'RocketHideout GruntMini2' : "Right Rocket Grunt - Hideout",
    'RocketHideout Giovanni1' : "Giovanni - Rocket Hideout",
    'Lavender Channeler' : "Channeler Ruth - Pokemon Tower",
    'Lavender Rocket1' : "Rocket Grunt 1 - Lavender Tower",
    'Lavender Rocket2' : "Rocket Grunt 2 - Lavender Tower",
    'Lavender Rocket3' : "Rocket Grunt 3 - Lavender Tower",
    'Route16 Biker1' : "Biker Lao - Route 16",
    'Route16 Biker2' : "Cue Ball Luke - Route 16",
    'Route16 Biker3' : "Cue Ball Koji - Route 16",
    'Route16 Biker4' : "Biker Hideo - Route 16",
    'Route16 Biker5' : "Biker Ruben - Route 16",
    'Route16 Biker6' : "Cue Ball Camron Route 16",
    'Route18 Biker1' : "Biker William - Route 18",
    'Route18 Trainer1' : "Bird Keeper Jacob - Route 18",
    'Route18 Trainer2' : "Dragon Tamer Ramiro - Route 18",
    'Route18 Trainer3' : "Ace Trainer Wilton - Route 18",
    'Route13 Trainer1' : "Bird Keeper Sebastian - Route 13",
    'Route13 Trainer2' : "Picnicker Susie - Route 13",
    'Route13 Trainer3' : "Picnicker Alma - Route 13",
    'Route13 Trainer4' : "Beauty Lola - Route 13",
    'Route13 Trainer5' : "Beauty Sheila - Route 13",
    'Route13 Trainer6' : "Bird Keeper Perry - Route 13",
    'Route13 Trainer7' : "Biker Jared - Route 13",
    'Route13 Trainer8' : "Bird Keeper Robert - Route 13",
    'Route12 Electrician' : "Rocket Luca - Route 12",
    'Route12 Cooltrainer' : "Camper Justin - Route 12",
    'Route12 Fisherman' : "Fisherman Andrew - Route 12",
    'SilphCo GarySquirtle' : "Rival [Charmander] - Silph Co",
    'SilphCo GaryBulba' : "Rival [Squirtle] - Silph Co",
    'SilphCo GaryChar' : "Rival [Bulbasaur] - Silph Co",
    'SilphCo Ariana' : "Ariana - Silph Co",
    'SilphCo Archer' : "Archer - Silph Co",
    'SilphCo Giovanni' : "Giovanni - Silph Co",
    'Saffron Chuck' : "Chuck - Saffron City", 
    'Saffron Sabrina' : "Sabrina - Saffron City",
    'Saffron DumbassKid' : "Dumbass Kid - Saffron City", 
    'Pewter BrockRematch' : "Brock Rematch - Pewter City",
    'Cerulean MistyRematch' : "Misty Rematch - Cerulean City",
    'Vermilion LtSurgeRematch' : "Lt. Surge - Vermillion City",
    'Route8 CentiMiniBoss' : "Centiskorch Boss - Route 8",
    'Celadon Flapple1' : "Pokemon Trainer Sam - Celadon Hotel",
    'Celadon Flapple2' : "Pokemon Trainer Shelly - Celadon Hotel",
    'Fuschia Sandacondite' : "Pokemon Trainer Hailey - Route 15",
    'Fuschia KogaGymTrainer' : "Juggler Kayden - Fuschia Gym",
    'Fuschia Brendan' : "Brendan - Safari Zone",
    'Fuschia Koga' : "Koga - Fuschia City",
    'Seafoam Pryce1' : "Pryce 1 - Seafoam Islands", 
    'Seafoam Pryce2' : "Pryce 2 - Seafoam Islands", 
    'Seafoam Pryce3' : "???", 
    'Celadon ErikaRe' : "Erika Rematch - Celadon Gym", 
    'Cinnabar May' : "May - Cinnabar Island",
    'Cinnabar Mansion1' : "Miniboss 1 - Cinnabar Mansion",
    'Cinnabar Mansion2' : "Burglar Lewis - Cinnabar Mansion",
    'Cinnabar Jasmine' : "Jasmine - Cinnabar Island", 
    'Cinnabar Blaine' : "Blaine - Cinnabar Gym",
    'CeruleanCave Grunt1' : "Team Rocket Grunt 1 - Cerulean Cave",
    'CeruleanCave Grunt2' : "Team Rocket Grunt 2 - Cerulean Cave",
    'CeruleanCave Archer' : "Archer - Cerulean Cave",
    'CeruleanCave Ariana' : "Ariana - Cerulean Cave",
    'CeruleanCave Giovanni' : "Giovanni - Cerulean Cave",
    'CeruleanCave Ketchup1' : "Apprentice Ketchup 1 - Cerulean Cave",
    'CeruleanCave Ketchup2' : "Apprentice Ketchup 2 - Cerulean Cave",
    'Viridian Clair' : "Clair - Viridian Gym",
    'Viridian GaryPreE4Charmander' : "Rival 4 [Bulbasaur] - Route 22",
    'Viridian GaryPreE4Bulbasaur' : "Rival 4 [Squirtle] - Route 22",
    'Viridian GaryPreE4Squirtle' : "Rival 4 [Charmander] - Route 22",
    'Viridian BrendanFinal' : "Brendan - Victory Road",
    'VictoryRoad AceTrainer1' : "Ace Trainer Naomi - Victory Road",
    'VictoryRoad AceTrainer2' : "Ace Trainer Rolando - Victory Road",
    'VictoryRoad AceTrainer3' : "Ace Trainer George - Victory Road",
    'VictoryRoad AceTrainer4' : "Ace Trainer Caroline - Victory Road",
    'VictoryRoad AceTrainer5' : "Ace Trainer Colby - Victory Road",
    'VictoryRoad AceTrainer6' : "Ace Trainer Alexa - Victory Road",
    'VictoryRoad AceTrainer7' : "Cool Couple Ray and Tyra - Victory Road",
    'E4 LoreleiRain' : "Lorelei Rain",
    'E4 LoreleiHail' : "Lorelei Hail",
    'E4 Bruno1' : "Bruno 1",
    'E4 Bruno2' : "Bruno 2",
    'E4 Agatha1' : "Agatha",
    'E4 Agatha2' : "???",
    'E4 Lance1' : "Lance",
    'E4 Lance2' : "???",
    'E4 GarySquirtle' : "Rival Champion [Charmander]",
    'E4 GaryBulbasaur' : "Rival Champion [Squirtle]",
    'E4 GaryCharmander' : "Rival Champion [Bulbasaur]",
    'Pryce Rematch' : "Pryce Post Game - Seafoam Islands",
    'OneIsl Bugsy' : "Bugsy Post Game - One Island",
    'CapeBrink DHBattle' : "Channeler Rachel Post Game - Cape Brink",
    'Cerulean MistyPostGame' : "Misty Post Game - Cerulean City",
    'Viridian ClairPostGame' : "Clair Post Game - Viridian City",
    'Saffron DumbassKidPostGame' : "Clair Post Game - Saffron City",
    'TreasureBeach Red' : "Red - Treasure Beach",
    'Falkner Rematch' : "Falkner Post Game - Pewter City",
    'MtEmber Ariana' : "Ariana Post Game - Mt Ember",
    'MtEmber Archer' : "Archer Post Game - Mt Ember",
    'ThreeIsland Biker1' : "Biker 1 Post Game - Three Island",
    'ThreeIsland Biker2' : "Biker 2 Post Game - Three Island",
    'ThreeIsland Biker3' : "Biker 3 Post Game - Three Island",
    'ThreeIsland Biker4' : "Biker 4 Post Game - Three Island",
    'PuzzleBattleShedinja' : "???",
    'PuzzleBattleTeacher' : "???",
    'PuzzleBattlePostgame' : "???",
    'PuzzleBattlePostgameTwo' : "???",
    'RentalBattleEevee' : "???",
    'RentalGambler' : "???",
    }